### PR TITLE
Revert back to Dockerfile

### LINKED ISSUE #15: Update to the latest sage in preparation for live doc
I am rebooting sage live doc efforts 

https://github.com/sagemath/sage/pull/36144

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #15, and prepare for https://github.com/sagemath/sage/pull/36144.

This PR refreshes the repo in the master branch from ground up, by pulling in https://github.com/kwankyu/sage-binder-env

- We go back to Dockerfile to create the Binder environment.
- Removed mostly out-dated or obsolete files and contents. 
- Updated the notebook "Start here" kept in `notebooks` directory
- We use JupyterLab instead of classical Jupyter notebook.

The base sagemath image used is the develop version created by `https://github.com/sagemath/sage/blob/develop/.github/workflows/push_to_docker_hub.yml` Hence it is the most recent available.

### CODE REVIEW

**Comment by kwankyu** [comment]
@dimpase, may I get maintainer role for this repo? 

I want to act quickly when there is a problem with it, or when there is an improvement.

**Comment by kwankyu** [comment]
I want to act quickly when there is a problem with it, or when there is an improvement.

**Comment by dimpase** [comment]
@kwankyu - done.

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
